web:
  build: .
  command: python manage.py server
  volumes:
    - .:/app
  links:
    - db
  ports:
    - "9000:9000"
  environment:
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_HOST=db
    - DB_PORT=5432

db:
  image: postgres
